<script src="{{ asset('vendor/global/global.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/bootstrap-select/dist/js/bootstrap-select.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/chart.js/Chart.bundle.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/peity/jquery.peity.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/apexchart/apexchart.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendor/owl-carousel/owl.carousel.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/dashboard/dashboard-1.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/custom.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/deznav-init.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/demo.js') }}" type="text/javascript"></script>
<script src="{{ asset('js/styleSwitcher.js') }}" type="text/javascript"></script>
